// Save as: src/App.js
import React, { useState } from 'react';

// --- Simple, safe backend resolver ---
const API_BASE =
  process.env.REACT_APP_API_BASE ||
  (typeof window !== 'undefined' && window.location.hostname === 'localhost'
    ? 'http://127.0.0.1:5000'
    : 'https://ai4u-top10-backend.vercel.app');

const BACKEND_API = `${API_BASE}/api/generate-list`;

function App() {
  const [prompt, setPrompt] = useState('');
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);

  const generateList = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setResult(null);

    try {
      const response = await fetch(BACKEND_API, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: prompt.trim(),
          email: email.trim(),
        }),
      });
      const data = await response.json();
      setResult(data);
    } catch (err) {
      setResult({ success: false, error: 'Network error — please try again.' });
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (!result || !result.success) return;

    const htmlContent = `
<div style="max-width:800px;margin:0 auto;font-family:Arial,sans-serif;">
  <h1 style="color:#232F3E;text-align:center;">${result.title}</h1>
  <p style="color:#565959;text-align:center;margin:20px 0;">${result.intro}</p>
  ${result.products
    .map(
      (p, i) => `
  <div style="border:1px solid #ddd;margin:10px 0;padding:15px;border-radius:8px;">
    <h3 style="color:#232F3E;">${i + 1}. ${p.title}</h3>
    ${p.image_url ? `<img src="${p.image_url}" alt="${p.title}" style="max-width:140px;border-radius:8px;margin:8px 0;display:block;" />` : ''}
    <p><strong>Price:</strong> ${p.price}</p>
    <p><strong>Rating:</strong> ${p.rating}/5 ⭐</p>
    <p>${p.description}</p>
    <a href="${p.affiliate_link}" target="_blank" rel="noopener" style="background:#FF9900;color:#fff;padding:10px 20px;text-decoration:none;border-radius:6px;display:inline-block;margin-top:8px;">View on Amazon</a>
  </div>`
    )
    .join('')}
  <p style="text-align:center;color:#565959;font-size:12px;margin-top:30px;">Generated by AI4U Top 10 Lists</p>
</div>`.trim();

    navigator.clipboard.writeText(htmlContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const shareToFacebook = () => {
    const url = encodeURIComponent(window.location.href);
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${url}`, '_blank');
  };

  const shareToTwitter = () => {
    const url = encodeURIComponent(window.location.href);
    const text = encodeURIComponent('Check out this AI-researched Top 10 list!');
    window.open(`https://twitter.com/intent/tweet?url=${url}&text=${text}`, '_blank');
  };

  return (
    <div
      style={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg,#4338ca 0%,#7c3aed 50%,#ec4899 100%)',
        padding: '20px',
        color: 'white',
        fontFamily: 'Arial, sans-serif',
      }}
    >
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
          <h1 style={{ fontSize: '3rem', fontWeight: 'bold', marginBottom: '16px' }}>
            AI4U Top 10 Lists ✨
          </h1>
          <p style={{ fontSize: '1.2rem', opacity: 0.9, maxWidth: '640px', margin: '0 auto' }}>
            AI-Researched & Endorsed Amazon Products — Real data and working affiliate links!
          </p>
        </div>

        {/* Input Section */}
        <div style={{ maxWidth: '600px', margin: '0 auto 40px auto' }}>
          <div
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '20px',
              padding: '30px',
              border: '1px solid rgba(255,255,255,0.2)',
            }}
          >
            <div style={{ marginBottom: '20px' }}>
              <label
                style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '8px' }}
              >
                What products are you looking for?
              </label>
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g., fantasy football trophies, organic chips, gaming laptops…"
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: '8px',
                  border: '1px solid rgba(255,255,255,0.3)',
                  background: 'rgba(255,255,255,0.2)',
                  color: 'white',
                  fontSize: '16px',
                  outline: 'none',
                  boxSizing: 'border-box',
                }}
                onKeyDown={(e) => e.key === 'Enter' && !loading && generateList()}
              />
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label
                style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '8px' }}
              >
                Email address (optional — to receive your list)
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="leehanna8@gmail.com"
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: '8px',
                  border: '1px solid rgba(255,255,255,0.3)',
                  background: 'rgba(255,255,255,0.2)',
                  color: 'white',
                  fontSize: '16px',
                  outline: 'none',
                  boxSizing: 'border-box',
                }}
              />
            </div>

            <button
              onClick={generateList}
              disabled={loading || !prompt.trim()}
              style={{
                width: '100%',
                padding: '15px',
                background: loading
                  ? '#666'
                  : 'linear-gradient(135deg,#9333ea 0%,#ec4899 100%)',
                color: 'white',
                border: 'none',
                borderRadius: '8px',
                fontSize: '18px',
                fontWeight: 600,
                cursor: loading ? 'not-allowed' : 'pointer',
              }}
            >
              {loading ? 'Researching products…' : 'Generate Top 10 List'}
            </button>
          </div>
        </div>

        {/* Results */}
        {result && (
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            {result.success ? (
              <div
                style={{
                  background: 'rgba(255,255,255,0.1)',
                  borderRadius: '20px',
                  padding: '30px',
                  border: '1px solid rgba(255,255,255,0.2)',
                }}
              >
                {/* Result header */}
                <div style={{ marginBottom: '30px' }}>
                  <h2 style={{ fontSize: '2rem', fontWeight: 'bold', marginBottom: '8px' }}>
                    {result.title}
                  </h2>
                  <p style={{ opacity: 0.9, marginBottom: '8px' }}>{result.intro}</p>
                  <p style={{ fontSize: '14px', color: '#86efac' }}>
                    ✅ All products have REAL Amazon ASINs and working affiliate links!
                  </p>
                  {email && (
                    <p style={{ fontSize: '14px', color: '#93c5fd', marginTop: '4px' }}>
                      📧 Results sent to your email
                    </p>
                  )}
                </div>

                {/* Action buttons */}
                <div style={{ marginBottom: '30px', display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                  <button
                    onClick={copyToClipboard}
                    style={{
                      background: '#16a34a',
                      color: 'white',
                      padding: '10px 20px',
                      border: 'none',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      fontSize: '14px',
                      fontWeight: 500,
                    }}
                  >
                    {copied ? '✅ Copied!' : '📋 Copy HTML'}
                  </button>
                  <button
                    onClick={shareToFacebook}
                    style={{
                      background: '#1877f2',
                      color: 'white',
                      padding: '10px 20px',
                      border: 'none',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      fontSize: '14px',
                    }}
                  >
                    📘 Share on Facebook
                  </button>
                  <button
                    onClick={shareToTwitter}
                    style={{
                      background: '#1da1f2',
                      color: 'white',
                      padding: '10px 20px',
                      border: 'none',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      fontSize: '14px',
                    }}
                  >
                    🐦 Share on Twitter
                  </button>
                </div>

                {/* Products list */}
                <div style={{ display: 'grid', gap: '16px' }}>
                  {result.products &&
                    result.products.map((product, index) => (
                      <div
                        key={product.asin || index}
                        style={{
                          background: 'rgba(255,255,255,0.2)',
                          borderRadius: '12px',
                          padding: '20px',
                          border: '1px solid rgba(255,255,255,0.3)',
                        }}
                      >
                        <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px' }}>
                          {/* Rank bubble */}
                          <div
                            style={{
                              width: '48px',
                              height: '48px',
                              background: 'linear-gradient(135deg,#9333ea 0%,#ec4899 100%)',
                              borderRadius: '50%',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center',
                              color: 'white',
                              fontWeight: 'bold',
                              fontSize: '18px',
                              flexShrink: 0,
                            }}
                          >
                            {index + 1}
                          </div>

                          {/* Details */}
                          <div style={{ flex: 1 }}>
                            <h3 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '8px' }}>
                              {product.title}
                            </h3>

                            {/* 🔑 IMAGE now on the site */}
                            {product.image_url && (
                              <img
                                src={product.image_url}
                                alt={product.title}
                                style={{
                                  maxWidth: '140px',
                                  borderRadius: '8px',
                                  marginBottom: '10px',
                                  display: 'block',
                                }}
                              />
                            )}

                            <div style={{ marginBottom: '8px' }}>
                              <span
                                style={{
                                  color: '#86efac',
                                  fontWeight: 'bold',
                                  fontSize: '1.25rem',
                                  marginRight: '16px',
                                }}
                              >
                                {product.price}
                              </span>
                              <span>⭐ {product.rating}/5</span>
                            </div>

                            <p style={{ opacity: 0.9, fontSize: '14px', marginBottom: '12px' }}>
                              {product.description}
                            </p>

                            <div
                              style={{
                                display: 'flex',
                                gap: '8px',
                                alignItems: 'center',
                                flexWrap: 'wrap',
                              }}
                            >
                              <a
                                href={product.affiliate_link}
                                target="_blank"
                                rel="noopener noreferrer"
                                style={{
                                  background: '#f97316',
                                  color: 'white',
                                  padding: '8px 16px',
                                  textDecoration: 'none',
                                  borderRadius: '6px',
                                  fontSize: '14px',
                                  fontWeight: 500,
                                }}
                              >
                                🛒 View on Amazon
                              </a>
                              <span style={{ fontSize: '12px', color: '#86efac', padding: '4px 8px' }}>
                                ASIN: {product.asin}
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                </div>

                {/* Footer */}
                <div
                  style={{
                    marginTop: '30px',
                    paddingTop: '20px',
                    borderTop: '1px solid rgba(255,255,255,0.2)',
                    textAlign: 'center',
                  }}
                >
                  <p style={{ fontSize: '14px', opacity: 0.8 }}>
                    Generated: {result.generated_at} | Affiliate ID: {result.affiliate_id}
                  </p>
                </div>
              </div>
            ) : (
              <div
                style={{
                  background: 'rgba(239,68,68,0.2)',
                  border: '1px solid rgba(239,68,68,0.5)',
                  borderRadius: '8px',
                  padding: '16px',
                }}
              >
                <p style={{ color: '#fca5a5' }}>Error: {result.error}</p>
              </div>
            )}
          </div>
        )}

        {/* Features (bottom tiles) */}
        <div
          style={{
            maxWidth: '1000px',
            margin: '40px auto 0 auto',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
            gap: '16px',
          }}
        >
          <div
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '12px',
              padding: '20px',
              border: '1px solid rgba(255,255,255,0.2)',
              textAlign: 'center',
            }}
          >
            <h3 style={{ fontWeight: 600, marginBottom: '8px' }}>🎯 Unlimited Categories</h3>
            <p style={{ fontSize: '14px', opacity: 0.8 }}>
              From potato chips to baby products — any category works!
            </p>
          </div>
          <div
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '12px',
              padding: '20px',
              border: '1px solid rgba(255,255,255,0.2)',
              textAlign: 'center',
            }}
          >
            <h3 style={{ fontWeight: 600, marginBottom: '8px' }}>✅ Real Amazon Data</h3>
            <p style={{ fontSize: '14px', opacity: 0.8 }}>
              Actual ASINs, current prices, real customer ratings
            </p>
          </div>
          <div
            style={{
              background: 'rgba(255,255,255,0.1)',
              borderRadius: '12px',
              padding: '20px',
              border: '1px solid rgba(255,255,255,0.2)',
              textAlign: 'center',
            }}
          >
            {/* 🔄 Text changed per your request */}
            <h3 style={{ fontWeight: 600, marginBottom: '8px' }}>📧 Results Sent</h3>
            <p style={{ fontSize: '14px', opacity: 0.8 }}>Results sent to your email</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
